### ISSUE TITLE
hi what's the diff

### ISSUE THREAD

**Issue by augmen** [rasmusbergpalm/evostrat#2]
hi what's the difference between this -- [https://github.com/alirezamika/evostra](url) and your repo ?

**Comment by rasmusbergpalm** [comment]
The library you linked is different in many ways

1. It's limited to sampling from a normal distribution
1. It's limited to use SGD
1. It limits you to use the policy networks defined in the library whereas this let's you easily use any `nn.Module`
1. It takes control over your optimization loop, whereas this library let's you handle that. This let's you add logging, checkpointing etc.
